In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [101]:
df=pd.read_csv('Titanic.csv',usecols=['Age','Fare','Survived'])

In [102]:
df

,Survived,Age,Fare
0,0,22.0,7.2500
1,1,38.0,71.2833
2,1,26.0,7.9250
3,1,35.0,53.1000
4,0,35.0,8.0500
...,...,...,...
886,0,27.0,13.0000
887,1,19.0,30.0000
888,0,NaN,23.4500
889,1,26.0,30.0000


In [103]:
from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [104]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [105]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [106]:
x_train

,Age,Fare
331,45.5,28.5000
733,23.0,13.0000
382,32.0,7.9250
704,26.0,7.8542
813,6.0,31.2750
...,...,...
106,21.0,7.6500
270,NaN,31.0000
860,41.0,14.1083
435,14.0,120.0000


In [107]:
# using simple imputer  we will compare it with missing indicator
si=SimpleImputer()
x_train_trf=si.fit_transform(x_train)
x_test_trf=si.transform(x_test)

In [108]:
x_train_trf

array([[ 45.5   ,  28.5   ],
       [ 23.    ,  13.    ],
       [ 32.    ,   7.925 ],
       ...,
       [ 41.    ,  14.1083],
       [ 14.    , 120.    ],
       [ 21.    ,  77.2875]], shape=(712, 2))

In [109]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
clf=LogisticRegression()
clf.fit(x_train_trf,y_train)
y_pred=clf.predict(x_test_trf)

In [110]:
accuracy_score(y_test,y_pred)

0.6480446927374302

In [111]:
# now we using missing indicator
mi=MissingIndicator()
mi.fit(x_train)

,missing_values,nan
,features,'missing-only'
,sparse,'auto'
,error_on_new,True


In [112]:
mi.features_        # this tell wear is the missing value show in 1 col the missing value s present 

array([0])

In [113]:
x_train_missing=mi.transform(x_train)

In [114]:
x_train_missing    #it is the new col which have new vlues t,f

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [115]:
x_test_missing=mi.transform(x_test)

In [116]:
# now we make new col and add all this new values
x_train['Age_miss']=x_train_missing
x_test['Age_miss']=x_test_missing

In [117]:
x_train           # now see the indicator col which have if value is nul show true if present show false

,Age,Fare,Age_miss
331,45.5,28.5000,False
733,23.0,13.0000,False
382,32.0,7.9250,False
704,26.0,7.8542,False
813,6.0,31.2750,False
...,...,...,...
106,21.0,7.6500,False
270,NaN,31.0000,True
860,41.0,14.1083,False
435,14.0,120.0000,False


In [118]:
# now if the missing indicator is usd
si=SimpleImputer()

x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [119]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
clf=LogisticRegression()
clf.fit(x_train_trf2,y_train)
y_pred=clf.predict(x_test_trf2)

In [120]:
accuracy_score(y_test,y_pred)

0.6368715083798883

In [121]:
# we also used direct parameter of idicator with out using the missing indicator class separate

In [122]:
si=SimpleImputer(add_indicator=True)

In [123]:
x_train=si.fit_transform(x_train)
x_test=si.transform(x_test)

In [124]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
clf=LogisticRegression()
clf.fit(x_train_trf2,y_train)
y_pred=clf.predict(x_test_trf2)

In [125]:
accuracy_score(y_test,y_pred)

0.6368715083798883

In [126]:
# so we do with out use missin indicator class